name: Build app

on: [push, workflow_dispatch]

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: 17
            cache: gradle
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :packageReleaseDeb
      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: build/compose/binaries/main-release/deb/*.deb
  exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :packageReleaseExe
      - uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/compose/binaries/main-release/exe/*.exe
